services:
  postgres:
    image: postgres:16-alpine
    container_name: db_len_tech_test_muamar
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lentechtest
      POSTGRES_DB: geo_entities
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d

volumes:
  pgdata:
